server {
  listen 8099;
  server_name _;
  root /www;
  index index.html;

  allow 172.30.32.2;
  deny all;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /dashboard {
    try_files /dashboard-steuerung.html =404;
  }

  location = /dashboard/ {
    return 302 /dashboard$is_args$args;
  }

  location = /ingress-info {
    default_type application/json;
    return 200 '{"ingress_path":"$http_x_ingress_path","hauptanwendung_pfad":"$http_x_ingress_path/","dashboard_pfad":"$http_x_ingress_path/dashboard"}';
  }

  location = /dashboard-steuerung.html {
    try_files $uri =404;
  }
}
