server {
  listen 8099;
  server_name _;
  root /www;
  index index.html;

  allow 172.30.32.2;
  deny all;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /dashboard-steuerung.html {
    try_files $uri =404;
  }
}
